### ISSUE TITLE
replace the boilerplate README.md

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/status-js-desktop#5]
Even a short description is better than that unrelated info.

**Comment by bgits** [comment]
This is a good point. Will have something shortly.

**Comment by bgits** [comment]
@stefantalpalaru There is a PR open here: https://github.com/status-im/status-js-desktop/pull/6

As a fresh set of eye, you are probably in the best position to tell what can be improved here.

And welcome to Status!

**Comment by stefantalpalaru** [comment]
Thanks!

Yes, the new README is much better.
