### ISSUE TITLE
install using `yarn` gives incompatibility

### ISSUE THREAD

**Issue by corpetty** [status-im/status-js-desktop#7]
cloned master branch, ran `yarn`, got the following:

```
petty@bean:~/GitHub/status-im/status-js-desktop$ yarn
yarn install v1.12.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
error electron-react-boilerplate@0.17.0: The engine "node" is incompatible with this module. Expected version ">=10.x <11". Got "8.11.3"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## other info
- yarn version:1.12.3
- node version: v8.11.3
- npm version: 5.5.1
- os: ubuntu 18.04.1 LTS

**Comment by jrainville** [comment]
The  minimum expected Node version is 10.

You can easily change Node version using NVM (https://github.com/creationix/nvm)

**Comment by bgits** [comment]
`package-lock.json` has been removed if you pull down the latest commit from master.

**Comment by samthomson** [comment]
Just pulled down master and got a similar error.

node 11.0.0
yarn 1.10.1
ubuntu 16.04

![image](https://user-images.githubusercontent.com/6588340/49273879-0ed09080-f4a9-11e8-84df-226139d75f2d.png)

**Comment by samthomson** [comment]
Okay, more than 10.x, my mistake. Changed to a 10 and it's working.
